const symbols: {
  [key: string]: string;
} = {
  "Architecture": "architecture",
  "Architecture, Planning and Landscape": "architecture",
  "Landscape Architecture": "landscape",
  "Planning": "location_city",
  "Sustainability Studies": "eco",
  "Academic Writing": "create",
  "African Studies": "public",
  "American Sign Language": "accessibility_new",
  "Anthropology": "psychology",
  "Arabic Language and Muslim Cultures": "language",
  "Archaeology": "museum",
  "Art": "palette",
  "Art History": "museum",
  "Arts": "palette",
  "Arts and Science Honours": "stars",
  "Canadian Studies": "public",
  "Central and East European Studies": "public",
  "Chinese": "language",
  "Communication and Culture": "forum",
  "Communication and Media Studies": "forum",
  "Dance": "theater_comedy",
  "Drama": "theater_comedy",
  "Earth Science": "terrain",
  "East Asian Language Studies": "language",
  "East Asian Studies": "public",
  "Economics": "attach_money",
  "English": "create",
  "Film": "movie",
  "French": "language",
  "Geography": "map",
  "Gender and Sexuality Studies": "people",
  "German": "language",
  "Global Development Studies": "public",
  "Greek": "language",
  "Greek and Roman Studies": "museum",
  "History": "history",
  "Indigenous Languages": "language",
  "Indigenous Studies": "public",
  "Innovation": "whatshot",
  "International Relations": "public",
  "Italian": "language",
  "Japanese": "language",
  "Language": "language",
  "Latin": "language",
  "Latin American Studies": "public",
  "Law and Society": "gavel",
  "Linguistics": "record_voice_over",
  "Museum and Heritage Studies": "museum",
  "Music": "music_note",
  "Music Education": "music_note",
  "Music Performance": "music_note",
  "Philosophy": "psychology",
  "Political Science": "public",
  "Psychology": "psychology",
  "Religious Studies": "public",
  "Romance Studies": "palette",
  "Russian": "language",
  "School of Creative and Performing Arts": "theater_comedy",
  "Slavic": "public",
  "Sociology": "people",
  "South Asian Studies": "public",
  "Spanish": "language",
  "Strategic Studies": "public",
  "Term Abroad Program": "flight",
  "Urban Studies": "location_city",
  "Wellbeing": "wellness",
  "Community Health Sciences": "local_hospital",
  "Community Rehabilitation": "accessible_forward",
  "Health and Society": "local_hospital",
  "Medical Precision Health": "local_hospital",
  "Medical Science": "local_hospital",
  "Medicine": "local_hospital",
  "Accounting": "attach_money",
  "Business Technology Management": "computer",
  "Energy Management": "local_gas_station",
  "Entrepreneurship and Innovation": "lightbulb",
  "Finance": "attach_money",
  "Leadership Studies": "psychology",
  "Management Studies": "psychology",
  "Marketing": "marketing",
  "Operations Management": "build",
  "Organizational Behaviour and Human Resources": "psychology",
  "Professional Land Management": "public",
  "Real Estate Studies": "location_city",
  "Risk Management and Insurance": "shield",
  "Strategy and Global Management": "public",
  "Supply Chain Management": "swap_horiz",
  "Tourism Management": "flight",
  "Kinesiology": "fitness_center",
  "Law": "gavel",
  "Nursing": "local_hospital",
  "Aerospace Engineering": "airplane_ticket",
  "Biomedical Engineering": "build",
  "Chemical Engineering": "build",
  "Civil Engineering": "build",
  "Computer Engineering": "computer",
  "Digital Engineering": "computer",
  "Electrical Engineering": "build",
  "Energy and Environment, Engineering": "eco",
  "Energy Engineering": "build",
  "Engineering": "build",
  "Engineering Foundations": "build",
  "Environmental Engineering": "eco",
  "Geomatics Engineering": "location_on",
  "Manufacturing Engineering": "build",
  "Mechanical Engineering": "build",
  "Petroleum Engineering": "local_gas_station",
  "Software Engineering for Engineers": "computer",
  "Actuarial Science": "calculator",
  "Astronomy": "brightness_3",
  "Astrophysics": "brightness_3",
  "Biochemistry": "build",
  "Biology": "nature_people",
  "Biostatistics": "calculator",
  "Cellular, Molecular and Microbial Biology": "build",
  "Chemistry": "science",
  "Computational Media Design": "computer",
  "Computer Science": "computer",
  "Data Science": "data_usage",
  "Ecology": "eco",
  "Environmental Science": "public",
  "Geology": "public",
  "Geophysics": "public",
  "Information Security and Privacy": "security",
  "Marine Science": "waves",
  "Mathematics": "calculate",
  "Medical Physics": "favorite",
  "Nanoscience": "grain",
  "Neuroscience": "psychology",
  "Physics": "flash_on",
  "Plant Biology": "eco",
  "Science": "science",
  "Software Engineering": "code",
  "Space Physics": "public",
  "Statistics": "analytics",
  "Zoology": "animal",
  "Social Work": "group",
  "Interprofessional Health Education": "local_hospital",
  "Veterinary Medicine": "pets",
  "Education": "school",
  "Education Bridge to Teaching": "school",
  "Educational Psychology": "psychology",
  "Educational Research": "research",
  "Co-operative Education": "group_work",
  "Energy and Environmental Systems": "public",
  "Internship": "work",
  "Public Policy": "policy",
  "Sustainable Energy Development": "public",
  "University": "school",
  "University Exchange": "swap_horizontal",
  "Transportation Studies": "traffic",
  "Dance Education": "dance",
  "Physical Education": "fitness_center",
  "Architectural Studies": "location_city",
  "Environmental Design": "public",
  "Landscape": "landscape",
  "Development Studies": "public",
  "Women's Studies": "wc",
  "Business and Environment": "public",
  "Environmental Design Architecture": "public",
  "Environmental Design Landscape": "public",
  "Environmental Design Planning": "public",
  "Comparative Literature": "menu_book",
  "Information Security": "security",
  "International Foundations Program": "public",
  "International Foundations Program Business": "public",
  "International Foundations Program Engineering": "public",
  "Fine Arts": "palette",
  "Humanities": "public",
  "Petroleum Land Management": "public",
  "Athletic Therapy": "fitness_center",
  "Israel Studies": "public",
  "Science, Technology and Society": "public",
  "Applied Mathematics": "calculate",
  "Pure Mathematics": "calculate",
  "Human Resources and Organizational Dynamics": "people",
  "Communications Studies": "forum",
  "Interdisciplinary Studies": "public",
  "Management Information Systems": "public",
  "Nursing Offsite": "local_hospital",
  "Culture and Society": "public",
  "Continuing Education": "school",
  "Botany": "eco",
  "English For Academic Purposes Program": "menu_book",
  "default": "public",
};

export default symbols;
