name: CI Server

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**

jobs:
  format-check:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}--job1
    steps:
      - name: git-clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install pip

      - name: check
        run: |
          cd server
          pip install -r ./requirements.txt
          pylint ./src

  test:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}--job2
    steps:
      - name: git-clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install pip
          sudo apt-get -y install git-lfs
          git lfs install
          git lfs pull

      - name: test-server
        run: |
          echo ${{ secrets.NOT_CONNECTION_STRING }}
          export NOT_CONNECTION_STRING=${{ secrets.NOT_CONNECTION_STRING }}
          export CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}
          cd server/src
          pip install -r ../requirements.txt
          pytest test_app.py -s
