name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  format:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: git-clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install pip nodejs yarn

      - name: format-server
        run: |
          cd server
          pip install -r requirements.txt
          black --check .
      - name: format-client
        run: |
          cd client
          npm install
          npm run check-format
